/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Formularios;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Valentia
 */
public class frm_vehiculos extends javax.swing.JInternalFrame {

    DefaultTableModel modelo;

    private void mtd_encabezadoTabla() {
        String titulos[] = { "Placa", "Marca", "Modelo", "Año", "Precio"};
        modelo = new DefaultTableModel(null, titulos);
        tbl_carros.setModel(modelo);
    }

    public frm_vehiculos() {
        initComponents();
        mtd_encabezadoTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_precio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_agregar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_carros = new javax.swing.JTable();
        txt_modelo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_eliminar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_placa = new javax.swing.JTextField();
        txt_marca = new javax.swing.JTextField();
        txt_año = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        txt_precio.addActionListener(this::txt_precioActionPerformed);
        txt_precio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_precioKeyTyped(evt);
            }
        });

        jLabel1.setText("CEDULA:");

        btn_agregar.setText("Agregar");
        btn_agregar.addActionListener(this::btn_agregarActionPerformed);

        jLabel2.setText("NOMBRE:");

        tbl_carros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbl_carros);

        jLabel3.setText("APELLIDO:");

        jLabel4.setText("Año:");

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(this::btn_eliminarActionPerformed);

        btn_editar.setText("Editar");
        btn_editar.addActionListener(this::btn_editarActionPerformed);

        jLabel6.setText("Precio:");

        txt_marca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_marcaKeyTyped(evt);
            }
        });

        txt_año.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_añoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_marca, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                            .addComponent(txt_año)
                            .addComponent(txt_placa)
                            .addComponent(txt_precio)
                            .addComponent(txt_modelo, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_agregar)
                        .addGap(42, 42, 42)
                        .addComponent(btn_eliminar)
                        .addGap(49, 49, 49)
                        .addComponent(btn_editar)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregar)
                    .addComponent(btn_eliminar)
                    .addComponent(btn_editar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_marcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_marcaKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isLetter(c) && c != ' ') {
        evt.consume();
            
           
        }
    }//GEN-LAST:event_txt_marcaKeyTyped

    private void txt_añoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_añoKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_añoKeyTyped

    private void txt_precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_precioActionPerformed

    
    private void txt_precioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_precioKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '.') {
            evt.consume();
        }
    }//GEN-LAST:event_txt_precioKeyTyped

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {
        String accion = btn_agregar.getText();
        try {
            if (accion.equalsIgnoreCase("Agregar")) {
                if (validarRepeticionCedula()) {
                    JOptionPane.showMessageDialog(null, "Error: La marca ya existe. Ingrese una diferente.");
                    return;
                }
                
                if (validarRepeticionSeguro()) {
                    JOptionPane.showMessageDialog(null, "Error: El año ya existe. Ingrese una diferente.");
                    return;
                }

                
                if (validacion()) {
                    Clases.cls_vehi objeto = new Clases.cls_vehi(
                            txt_placa.getText(),
                            txt_marca.getText(),
                            txt_modelo.getText(),
                            Integer.parseInt(txt_año.getText()),
                            Double.parseDouble(txt_precio.getText()));

                    modelo = (DefaultTableModel) tbl_carros.getModel();

                      String nuevaFila[] = {
                        objeto.getPlaca(),
                        objeto.getMarca(),
                        objeto.getModelo(),
                        String.valueOf(objeto.getAño()),
                        String.valueOf(objeto.getPrecio()),
                    };

                    modelo.addRow(nuevaFila);
                    mtd_limpiartextos();
                }
            } else if (accion.equalsIgnoreCase("Actualizar")) {
                int filasel = tbl_carros.getSelectedRow();
                if (filasel == -1) {
                    JOptionPane.showMessageDialog(null, "Por favor seleccione una fila");
                    return;
                }

                if (validacion()) {
                    Clases.cls_vehi objeto = new Clases.cls_vehi(
        txt_placa.getText(),
        txt_marca.getText(),
        txt_modelo.getText(),
        Integer.parseInt(txt_año.getText()),
        Double.parseDouble(txt_precio.getText()));

                    tbl_carros.setValueAt(txt_placa.getText(), filasel, 0);
                    tbl_carros.setValueAt(txt_marca.getText(), filasel, 1);
                    tbl_carros.setValueAt(txt_modelo.getText(), filasel, 2);
                    tbl_carros.setValueAt(txt_año.getText(), filasel, 3);
                    tbl_carros.setValueAt(txt_precio.getText(), filasel, 4);

                    mtd_limpiartextos();
                    btn_agregar.setText("Agregar");
                }
            }
        } catch (HeadlessException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            int filasel = tbl_carros.getSelectedRow();
            if (filasel == -1) {
                JOptionPane.showMessageDialog(null, "Por favor selecione una fila");
            } else {
                modelo = (DefaultTableModel) tbl_carros.getModel();
                modelo.removeRow(filasel);
            }
        } catch (HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            int filasel = tbl_carros.getSelectedRow();

            if (filasel == -1) {
                JOptionPane.showMessageDialog(null, "Por favor seleccione una fila");
                return;
            }

            
            txt_placa.setText(tbl_carros.getValueAt(filasel, 0).toString());
            txt_marca.setText(tbl_carros.getValueAt(filasel, 1).toString());
            txt_modelo.setText(tbl_carros.getValueAt(filasel, 2).toString());
            txt_año.setText(tbl_carros.getValueAt(filasel, 3).toString());
            txt_precio.setText(tbl_carros.getValueAt(filasel, 4).toString());

            btn_agregar.setText("Actualizar");

        } catch (HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    //metoso

    public void mtd_limpiartextos() {
        txt_modelo.setText("");
        txt_placa.setText("");
        txt_marca.setText("");
        txt_año.setText("");
        txt_precio.setText("");
    }

    private Boolean validacion() {
        if (txt_modelo.getText().length() <= 0) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el modelo", "Sistema de Vehiculos",
                    JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (txt_placa.getText().length() <= 0) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese la placa", "Sistema de Vehiculos",
                    JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (txt_marca.getText().length() <= 0) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese la marca", "Sistema de Vehiculos",
                    JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (txt_año.getText().length() <= 0) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el año", "Sistema de Vehiculos",
                    JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (txt_precio.getText().length() <= 0) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el precio", "Sistema de Vehiculos",
                    JOptionPane.INFORMATION_MESSAGE);
            return false;
        }

        return true;
    }

    private Boolean validarRepeticionCedula() {
        String codigoNuevo = txt_marca.getText();

        for (int i = 0; i < tbl_carros.getRowCount(); i++) {
            if (tbl_carros.getValueAt(i, 1).toString().equalsIgnoreCase(codigoNuevo)) {
                return true;
            }
        }

        return false;
    }
    
    private Boolean validarRepeticionSeguro() {
        String codigoNuevo = txt_año.getText();

        for (int i = 0; i < tbl_carros.getRowCount(); i++) {
            if (tbl_carros.getValueAt(i, 3).toString().equalsIgnoreCase(codigoNuevo)) {
                return true;
            }
        }

        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_carros;
    private javax.swing.JTextField txt_año;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_placa;
    private javax.swing.JTextField txt_precio;
    // End of variables declaration//GEN-END:variables
}
